baseURL = "https://totsukawa-region.com/"
languageCode = "ja-jp"
title = "株式会社十津川地域創生研究所"
theme = "tella"

[params]
  showBlog = true
  mainSections = ['blog']
  description = "地域とともに未来をつくる"
  author = "株式会社十津川地域創生研究所"
[params.logo]
  main = "/images/logo.png"
  alt = "会社ロゴ"
  size = "h-14"  

[[params.heroSlides]]
  img = "/images/slider1.jpeg"

[[params.heroSlides]]
  img = "/images/slider2.jpeg"

[[params.heroSlides]]
  img = "/images/slider3.jpeg"

[[params.heroSlides]]
  img = "/images/slider4.jpeg"


[menu]
  [[menu.main]]
    name = "事業の概要"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "市場分析"
    url = "/analysis/"
    weight = 2

  [[menu.main]]
    name = "事業運営"
    url = "/operation/"
    weight = 3

  [[menu.main]]
    name = "マーケティング戦略"
    url = "/marketing/"
    weight = 4


  [[menu.main]]
    name = "お知らせ"
    url = "/blog/"
    weight = 5


  [[menu.main]]
    name = "お問い合わせ"
    url = "/contact/"
    weight = 6

  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1